import type { Metadata } from "next";
import "./globals.css";

import { Merriweather } from "next/font/google";
import { Nunito } from "next/font/google";
import { auth, signOut } from "@/auth";
import { SessionProvider } from "next-auth/react";

const NunitoFont = Nunito({
  subsets: ["cyrillic"],
  weight: ["300", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <section className="md:pt-5">
      <SessionProvider session={session}>{children}</SessionProvider>
    </section>
  );
}
