import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import BottomNav from "@/components/BottomNav";

import { Merriweather } from "next/font/google";
import { Nunito } from "next/font/google";
import { auth, signOut } from "@/auth";

const NunitoFont = Nunito({
  subsets: ["cyrillic"],
  weight: ["300", "900"],
  style: ["normal", "italic"],
});
const MerriweatherFont = Merriweather({
  subsets: ["latin"],
  weight: ["300", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  const SignOut = async () => {
    "use server";
    await signOut();
  };
  return (
    <html lang="en">
      <body className={NunitoFont.className}>
        <Header
          className={MerriweatherFont.className}
          session={session}
          SignOut={SignOut}
        />
        <div className="pt-14 md:pt-12">{children}</div>
        <BottomNav />
      </body>
    </html>
  );
}
