import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

import { Merriweather } from "next/font/google";
import { Nunito } from "next/font/google";

const NunitoFont = Nunito({
  subsets: ["cyrillic"],
  weight: ["300", "900"],
  style: ["normal", "italic"],
});
const MerriweatherFont = Merriweather({
  subsets: ["latin"],
  weight: ["300", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={NunitoFont.className}>
        <Header className={MerriweatherFont.className} />
        {children}
      </body>
    </html>
  );
}
